/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringFilter } from "../../util/StringFilter";
import { InvitationWhereUniqueInput } from "../../invitation/base/InvitationWhereUniqueInput";
import { ShoppingListWhereUniqueInput } from "../../shoppingList/base/ShoppingListWhereUniqueInput";

@InputType()
class UserWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  firstName?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: () => InvitationWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => InvitationWhereUniqueInput)
  @IsOptional()
  @Field(() => InvitationWhereUniqueInput, {
    nullable: true,
  })
  invitor?: InvitationWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => InvitationWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => InvitationWhereUniqueInput)
  @IsOptional()
  @Field(() => InvitationWhereUniqueInput, {
    nullable: true,
  })
  memberInvitations?: InvitationWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => ShoppingListWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ShoppingListWhereUniqueInput)
  @IsOptional()
  @Field(() => ShoppingListWhereUniqueInput, {
    nullable: true,
  })
  shoppingLists?: ShoppingListWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  username?: StringFilter;
}

export { UserWhereInput as UserWhereInput };
